name: Deploy to GitHub Pages

on:
  push:
    branches:
    - 'docs'
    paths:
    - 'docusaurus/**'
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: docusaurus/website
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'
          
      - name: Install
        working-directory: ./docusaurus/website
        run: npm install
      
      - name: Set credentials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action" 
      
      - name: Deploy
        working-directory: ./docusaurus/website
        run: npm run publish-gh-pages
              
